#######################################################################################################
# Qubrship custom template. ConfigMap for Kerberos configuration if Kerberos is enabled via Helm values
#######################################################################################################
{{- if .Values.kerberos.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-kerberos
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
data:
  {{- if .Values.kerberos }}
  krb5.conf: |
    {{- .Values.kerberos.config | nindent 4 }}
  {{- end }}
{{- end }}
