################################################################################################################################
# Qubership custom change: configmap-hue-extra.yaml and configmap-hue.yaml are converted to secret-hue.yaml for security reasons.
################################################################################################################################ 
{{- if .Values.kerberos.enabled }}
apiVersion: v1
metadata:
  name: keytabs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
data:
  {{- if .Values.kerberos.keytab }}
  service.keytab: |
    {{- .Values.kerberos.keytab | nindent 4 }}
  {{- end }}
kind: Secret
type: Opaque
{{- end }}
---
{{- if .Values.ssl.enabled }}
apiVersion: v1
metadata:
  name: cacerts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
data:
  {{- if .Values.ssl.cacerts }}
  cacerts.pem: |
    {{- .Values.ssl.cacerts | nindent 4 }}
  {{- end }}
kind: Secret
type: Opaque
{{- end }}
---
{{- if .Values.ldap.enabled }}
apiVersion: v1
metadata:
  name: scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
data:
  {{- if .Values.ldap.bind_password_script }}
  hue_passwords.sh: |
    {{- .Values.ldap.bind_password_script  | nindent 4 }}
  {{- end }}
kind: Secret
type: Opaque
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- include "allObjectsLabels" . | nindent 4 }}
stringData:
  z-hue.ini: |
{{ if .Values.hue.database.create }}
    [desktop]
    [[database]]
    engine={{ .Values.hue.database.engine }}
    user={{ include "postgres.hue.user" . }}
    host={{ include "postgres.host" . }}
    port={{ include "postgres.port" . }}
{{- if .Values.hue.database.password_script }}
    password_script={{ .Values.hue.database.password_script }}
{{- else }}
    password={{ include "postgres.hue.password" . }}
{{- end }}
    name={{ .Values.hue.database.name }}
{{ end }}

    [notebook]
    [[interpreters]]
    {{ tpl .Values.hue.interpreters . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config-extra
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- include "allObjectsLabels" . | nindent 4 }}
stringData:
  zz-hue.ini: |
    {{ tpl .Values.hue.ini . | indent 4 | trim }}
