##########################################################################################
# Qubership custom template: Secret with database connection credentials/configs for trino
##########################################################################################
{{- if .Values.databasescommon.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-databases
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
stringData:
{{- with .Values.databasescommon.configs }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}