##########################################################################################################################
# Qubership custom template. TLS certificate for Hue using cert-manager with custom DNS/IP SANs if enabled via Helm values
##########################################################################################################################
{{- define "certDnsNames" -}}
  {{- $dnsNames := list "localhost" "hue" (printf "%s.%s" "hue" .Release.Namespace) (printf "%s.%s.svc" "hue" .Release.Namespace) -}}
    {{- $dnsNames = concat $dnsNames .Values.certManagerInegration.subjectAlternativeName.additionalDnsNames -}}
  {{- $dnsNames | toYaml -}}
{{- end -}}
{{- define "certIpAddresses" -}}
  {{- $ipAddresses := list "127.0.0.1" -}}
  {{- $ipAddresses = concat $ipAddresses .Values.certManagerInegration.subjectAlternativeName.additionalIpAddresses -}}
  {{- $ipAddresses | toYaml -}}
{{- end -}}


{{- if .Values.certManagerInegration.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hue-certificate
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
    {{- include "certManagerLabel" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "-11"
spec:
  secretName: {{ .Values.certManagerInegration.secretName }}
  additionalOutputFormats:
    - type: CombinedPEM
  duration: {{ default 365 .Values.certManagerInegration.duration | mul 24 }}h
  renewBefore: 360h
  commonName: hue.svc
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
{{ ( include "certDnsNames" . | indent 4 ) }}
  ipAddresses:
{{ ( include "certIpAddresses" . | indent 4) }}
  issuerRef:
    group: cert-manager.io
  {{- if .Values.certManagerInegration.clusterIssuerName }}
    name: {{ .Values.certManagerInegration.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: hue-tls-issuer
    kind: Issuer
  {{- end }}
{{- end }}
