##########################################################################################################################
# Qubership custom template. Kubernetes Job to initialize the Hue PostgreSQL database if enabled via Helm values
##########################################################################################################################
{{ if .Values.hue.database.create }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "allObjectsLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.hue.database.initJobAnnotations | nindent 4}}
  name: {{ .Chart.Name }}-create-postgres-db
spec:
  activeDeadlineSeconds: 320
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: {{ .Chart.Name }}-create-postgres-db
    spec:
      activeDeadlineSeconds: 320
      containers:
        - name: {{ .Chart.Name }}-create-postgres-db
          env:
            - name: POSTGRES_HOST
              value: {{ include "postgres.host" . }}
            - name: POSTGRES_PORT
              value: "{{ include "postgres.port" . }}"
            - name: DB_NAME
              value: {{ .Values.hue.database.name }}
            - name: DB_USER
              value: {{ include "postgres.hue.user" . }}
            {{- if .Values.env }}
               {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: huepreinstallhooksecret
          image: {{ include "hue.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.hue.securityContext }}
          securityContext:
            {{- toYaml .Values.hue.securityContext | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.certManagerInegration.enabled }}
            {{- range .Values.certManagerInegration.secretMounts }}
            - name: {{ $.Values.certManagerInegration.secretName }}-volume
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
              {{- tpl (toYaml .Values.extraVolumeMounts) . | nindent 12 }}
            {{- end }}
          resources: {{- toYaml .Values.createDBJob.resources | nindent 12 }}
          command: ["/usr/share/hue/build/env/bin/python", "/bin/createdb.py"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        {{- if .Values.certManagerInegration.enabled}}
        - name: {{.Values.certManagerInegration.secretName }}-volume
          secret:
            secretName: {{.Values.certManagerInegration.secretName }}
        {{- end}}
        {{- if .Values.extraVolumes }}
          {{- tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        {{- toYaml .Values.hue.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
{{ end }}
