name: Lint Python File

on:
  push:
    branches:
      - '**'
    paths:
      - hue_docker/createdb.py
  pull_request:
    branches:
      - '**'
    paths:
      - hue_docker/createdb.py

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install psycopg2-binary pylint black flake8 mypy

      - name: Run black on createdb.py
        run: |
          black --check hue_docker/createdb.py  # --check is used to only check, not auto-format

      - name: Run flake8 on createdb.py
        run: |
          flake8 hue_docker/createdb.py

      - name: Run mypy on createdb.py
        run: |
          mypy hue_docker/createdb.py

      - name: Run pylint on createdb.py
        run: |
          pylint --disable=import-error hue_docker/createdb.py
